// ==============================================================
// Generated by Vitis HLS v
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="convEncoder_convEncoder,hls_ip_,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=0.801000,HLS_SYN_LAT=3,HLS_SYN_TPT=2,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=14,HLS_SYN_LUT=74,HLS_VERSION=}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module convEncoder (
        ap_clk,
        ap_rst_n,
        s_axis_TDATA,
        s_axis_TVALID,
        s_axis_TREADY,
        s_axis_TKEEP,
        s_axis_TSTRB,
        s_axis_TLAST,
        m_axis_TDATA,
        m_axis_TVALID,
        m_axis_TREADY,
        m_axis_TKEEP,
        m_axis_TSTRB,
        m_axis_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst_n;
input  [0:0] s_axis_TDATA;
input   s_axis_TVALID;
output   s_axis_TREADY;
input  [0:0] s_axis_TKEEP;
input  [0:0] s_axis_TSTRB;
input  [0:0] s_axis_TLAST;
output  [0:0] m_axis_TDATA;
output   m_axis_TVALID;
input   m_axis_TREADY;
output  [0:0] m_axis_TKEEP;
output  [0:0] m_axis_TSTRB;
output  [0:0] m_axis_TLAST;

 reg    ap_rst_n_inv;
reg   [6:0] shift_reg;
reg    s_axis_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
reg   [0:0] tmp_reg_210;
reg    ap_block_pp0_stage1_subdone_grp1_done_reg;
reg    ap_block_pp0_stage1_subdone_grp1;
reg    ap_block_pp0_stage1_subdone;
reg    m_axis_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_grp2;
reg   [0:0] tmp_reg_210_pp0_iter1_reg;
wire   [0:0] tmp_nbreadreq_fu_72_p6;
reg    ap_block_state3_pp0_stage0_iter1_grp2;
reg    ap_block_pp0_stage0_11001_grp2;
reg   [0:0] p_s_reg_214;
reg    ap_block_state2_pp0_stage1_iter0_grp1;
reg    ap_block_state4_pp0_stage1_iter1_grp1;
reg    ap_block_pp0_stage1_11001_grp1;
wire   [0:0] out0_fu_203_p2;
wire    regslice_both_m_axis_V_data_V_U_apdone_blk;
wire   [6:0] tmp_1_fu_139_p3;
reg    ap_block_pp0_stage1_01001_grp1;
reg    ap_block_pp0_stage0_01001_grp2;
wire   [5:0] lshr_ln_fu_129_p4;
wire   [0:0] tmp_3_fu_161_p3;
wire   [0:0] tmp_5_fu_177_p3;
wire   [0:0] tmp_2_fu_153_p3;
wire   [0:0] xor_ln29_1_fu_191_p2;
wire   [0:0] tmp_4_fu_169_p3;
wire   [0:0] xor_ln29_2_fu_197_p2;
wire   [0:0] xor_ln29_fu_185_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_11001;
wire    ap_idle_pp0_0to0;
reg    ap_reset_init_pp0;
reg    ap_block_pp0_stage1_11001;
wire    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_s_axis_V_data_V_U_apdone_blk;
wire   [0:0] s_axis_TDATA_int_regslice;
wire    s_axis_TVALID_int_regslice;
reg    s_axis_TREADY_int_regslice;
wire    regslice_both_s_axis_V_data_V_U_ack_in;
wire    regslice_both_s_axis_V_keep_V_U_apdone_blk;
wire   [0:0] s_axis_TKEEP_int_regslice;
wire    regslice_both_s_axis_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_V_strb_V_U_apdone_blk;
wire   [0:0] s_axis_TSTRB_int_regslice;
wire    regslice_both_s_axis_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_TLAST_int_regslice;
wire    regslice_both_s_axis_V_last_V_U_vld_out;
wire    regslice_both_s_axis_V_last_V_U_ack_in;
reg   [0:0] m_axis_TDATA_int_regslice;
reg    m_axis_TVALID_int_regslice;
wire    m_axis_TREADY_int_regslice;
wire    regslice_both_m_axis_V_data_V_U_vld_out;
wire    regslice_both_m_axis_V_keep_V_U_apdone_blk;
wire    regslice_both_m_axis_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_V_strb_V_U_apdone_blk;
wire    regslice_both_m_axis_V_strb_V_U_ack_in_dummy;
wire    regslice_both_m_axis_V_strb_V_U_vld_out;
wire    regslice_both_m_axis_V_last_V_U_apdone_blk;
wire    regslice_both_m_axis_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_V_last_V_U_vld_out;
reg    ap_condition_294;
reg    ap_condition_141;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 shift_reg = 7'd0;
#0 ap_CS_fsm = 2'd1;
#0 ap_block_pp0_stage1_subdone_grp1_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

convEncoder_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_TDATA),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_data_V_U_ack_in),
    .data_out(s_axis_TDATA_int_regslice),
    .vld_out(s_axis_TVALID_int_regslice),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_data_V_U_apdone_blk)
);

convEncoder_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_TKEEP),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_keep_V_U_ack_in),
    .data_out(s_axis_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_V_keep_V_U_vld_out),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_keep_V_U_apdone_blk)
);

convEncoder_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_TSTRB),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_strb_V_U_ack_in),
    .data_out(s_axis_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_V_strb_V_U_vld_out),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_strb_V_U_apdone_blk)
);

convEncoder_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_TLAST),
    .vld_in(s_axis_TVALID),
    .ack_in(regslice_both_s_axis_V_last_V_U_ack_in),
    .data_out(s_axis_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_V_last_V_U_vld_out),
    .ack_out(s_axis_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_V_last_V_U_apdone_blk)
);

convEncoder_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_TDATA_int_regslice),
    .vld_in(m_axis_TVALID_int_regslice),
    .ack_in(m_axis_TREADY_int_regslice),
    .data_out(m_axis_TDATA),
    .vld_out(regslice_both_m_axis_V_data_V_U_vld_out),
    .ack_out(m_axis_TREADY),
    .apdone_blk(regslice_both_m_axis_V_data_V_U_apdone_blk)
);

convEncoder_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd1),
    .vld_in(m_axis_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_TKEEP),
    .vld_out(regslice_both_m_axis_V_keep_V_U_vld_out),
    .ack_out(m_axis_TREADY),
    .apdone_blk(regslice_both_m_axis_V_keep_V_U_apdone_blk)
);

convEncoder_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd1),
    .vld_in(m_axis_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_V_strb_V_U_ack_in_dummy),
    .data_out(m_axis_TSTRB),
    .vld_out(regslice_both_m_axis_V_strb_V_U_vld_out),
    .ack_out(m_axis_TREADY),
    .apdone_blk(regslice_both_m_axis_V_strb_V_U_apdone_blk)
);

convEncoder_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(m_axis_TVALID_int_regslice),
    .ack_in(regslice_both_m_axis_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_TLAST),
    .vld_out(regslice_both_m_axis_V_last_V_U_vld_out),
    .ack_out(m_axis_TREADY),
    .apdone_blk(regslice_both_m_axis_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp1)) begin
                ap_block_pp0_stage1_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_s_reg_214 <= s_axis_TLAST_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_210 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        shift_reg <= tmp_1_fu_139_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_210 <= tmp_nbreadreq_fu_72_p6;
        tmp_reg_210_pp0_iter1_reg <= tmp_reg_210;
    end
end

assign ap_idle_pp0 = 1'b0;

assign ap_idle_pp0_0to0 = 1'b0;

always @ (*) begin
    if ((ap_idle_pp0_0to0 == 1'b1)) begin
        ap_reset_init_pp0 = 1'b1;
    end else begin
        ap_reset_init_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_reg_210_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_210 == 1'd1) & (1'b0 == ap_block_pp0_stage0_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_reg_210 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        m_axis_TDATA_blk_n = m_axis_TREADY_int_regslice;
    end else begin
        m_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((tmp_reg_210 == 1'd1)) begin
        if ((1'b1 == ap_condition_141)) begin
            m_axis_TDATA_int_regslice = p_s_reg_214;
        end else if ((1'b1 == ap_condition_294)) begin
            m_axis_TDATA_int_regslice = out0_fu_203_p2;
        end else begin
            m_axis_TDATA_int_regslice = 'bx;
        end
    end else begin
        m_axis_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (tmp_reg_210 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_reg_210 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        m_axis_TVALID_int_regslice = 1'b1;
    end else begin
        m_axis_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_210 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s_axis_TDATA_blk_n = s_axis_TVALID_int_regslice;
    end else begin
        s_axis_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_reg_210 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        s_axis_TREADY_int_regslice = 1'b1;
    end else begin
        s_axis_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((((1'b0 == ap_block_pp0_stage1_subdone) & (ap_reset_init_pp0 == 1'b0)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (ap_reset_init_pp0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_pp0_stage0_01001_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1_grp2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1_grp2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1_grp2));
end

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter1_grp2));
end

always @ (*) begin
    ap_block_pp0_stage1_01001_grp1 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_block_state4_pp0_stage1_iter1_grp1)) | ((1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_m_axis_V_data_V_U_apdone_blk == 1'b1) | ((1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_block_state4_pp0_stage1_iter1_grp1)))) | ((1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_block_state4_pp0_stage1_iter1_grp1)) | ((1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1)));
end

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((regslice_both_m_axis_V_data_V_U_apdone_blk == 1'b1) | ((1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_block_state4_pp0_stage1_iter1_grp1)))) | ((1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp1 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == ap_block_state4_pp0_stage1_iter1_grp1)) | ((1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage1_iter0_grp1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp1 = (((tmp_reg_210 == 1'd1) & (m_axis_TREADY_int_regslice == 1'b0)) | ((tmp_reg_210 == 1'd1) & (s_axis_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1_grp2 = ((tmp_reg_210 == 1'd1) & (m_axis_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage1_iter1_grp1 = ((tmp_reg_210_pp0_iter1_reg == 1'd1) & (m_axis_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_condition_141 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_01001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_294 = ((1'b0 == ap_block_pp0_stage1_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage1_01001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign lshr_ln_fu_129_p4 = {{shift_reg[6:1]}};

assign m_axis_TVALID = regslice_both_m_axis_V_data_V_U_vld_out;

assign out0_fu_203_p2 = (xor_ln29_fu_185_p2 ^ xor_ln29_2_fu_197_p2);

assign s_axis_TREADY = regslice_both_s_axis_V_data_V_U_ack_in;

assign tmp_1_fu_139_p3 = {{s_axis_TDATA_int_regslice}, {lshr_ln_fu_129_p4}};

assign tmp_2_fu_153_p3 = shift_reg[32'd6];

assign tmp_3_fu_161_p3 = shift_reg[32'd5];

assign tmp_4_fu_169_p3 = shift_reg[32'd4];

assign tmp_5_fu_177_p3 = shift_reg[32'd1];

assign tmp_nbreadreq_fu_72_p6 = s_axis_TVALID_int_regslice;

assign xor_ln29_1_fu_191_p2 = (tmp_5_fu_177_p3 ^ tmp_2_fu_153_p3);

assign xor_ln29_2_fu_197_p2 = (xor_ln29_1_fu_191_p2 ^ tmp_4_fu_169_p3);

assign xor_ln29_fu_185_p2 = (tmp_3_fu_161_p3 ^ s_axis_TDATA_int_regslice);

endmodule //convEncoder
